# Generated by Django 5.2.3 on 2025-07-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_adminreply_chatroom_message_userstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('punch_in', models.DateTimeField()),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(default='Present', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_records', to='attendance.employee')),
            ],
            options={
                'verbose_name_plural': 'Punch Records',
                'ordering': ['-date', '-punch_in'],
            },
        ),
    ]
