# Generated by Django 5.2.3 on 2025-07-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_punchinout_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Attendance Log', 'verbose_name_plural': 'Attendance Logs'},
        ),
        migrations.AddField(
            model_name='adminreply',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
