# Generated by Django 5.2.3 on 2025-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_messagereadreceipt_usermention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for late punch-out or other attendance notes', null=True),
        ),
    ]
