# Generated by Django 5.2.3 on 2025-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancelog_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateloginreason',
            name='expected_time',
            field=models.TimeField(blank=True, help_text='Expected time of arrival (HH:MM:SS)', null=True),
        ),
    ]
