# Generated by Django 4.2.7 on 2025-07-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendancepunchinout_delete_punchinout'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='late_login_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='attendance.lateloginreason'),
        ),
    ]
