# Generated by Django 4.2.7 on 2025-07-10 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0012_attendancelog_late_login_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('punch_in', models.DateTimeField(blank=True, null=True)),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('punch_in_time', models.CharField(blank=True, max_length=20)),
                ('punch_out_time', models.CharField(blank=True, max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('hours_worked', models.CharField(blank=True, default='0h 0m', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancepunchinout',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lateloginreason',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='lateloginreason',
            name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='dailyworkreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyworkreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dailyworkreport',
            unique_together={('user', 'date')},
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
        migrations.DeleteModel(
            name='AttendancePunchInOut',
        ),
        migrations.DeleteModel(
            name='LateLoginReason',
        ),
        migrations.RemoveField(
            model_name='dailyworkreport',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
