# Generated by Django 4.2.7 on 2025-07-11 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0013_attendance_remove_attendancepunchinout_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReasonApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reasons', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reason_approval', to='attendance.attendance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
